Coordinate github build

diff --git a/crates/support-scripts/ctl/container b/crates/support-scripts/ctl/container
--- a/crates/support-scripts/ctl/container
+++ b/crates/support-scripts/ctl/container
@@ -5,6 +5,13 @@ CONTAINER_NAME="e3-support.1"
 IMAGE="ghcr.io/gnosisguild/e3-support:$GIT_SHA"
 CACHE_PREFIX="e3-support"
 
+# Check if the image exists locally or remotely if not bail
+# Every time we push we build support so every build of enclave should have support built too.
+if ! docker image inspect "$IMAGE" >/dev/null 2>&1 && ! docker manifest inspect "$IMAGE" >/dev/null 2>&1; then
+    echo "Support scripts not found for git sha \"$GIT_SHA\" Please recompile the support scripts for this version of the enclave cli within the source repository"
+    exit 1
+fi
+
 # Function to cleanup
 cleanup() {
     echo "Stopping container and processes..."
